import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from '../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.massive,
    paddingBottom: spacing.xl,
    backgroundColor: colors.white,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backIcon: {
    fontSize: 28,
    color: colors.primary,
  },
  headerTitle: {
    fontSize: typography.fontSize.xxl,
    fontWeight: typography.fontWeight.semibold,
    color: colors.gray[800],
  },
  scrollContent: {
    padding: spacing.xl,
  },
  emptyContainer: {
    alignItems: 'center',
    paddingVertical: 60,
  },
  emptyIcon: {
    fontSize: 60,
    marginBottom: spacing.lg,
  },
  emptyText: {
    fontSize: typography.fontSize.xxl,
    fontWeight: typography.fontWeight.semibold,
    color: colors.gray[800],
    marginBottom: spacing.sm,
  },
  emptySubtext: {
    fontSize: typography.fontSize.base,
    color: colors.gray[500],
    textAlign: 'center',
  },
  methodsContainer: {
    marginBottom: spacing.xl,
  },
  methodCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: spacing.lg,
    marginBottom: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  methodLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  methodIcon: {
    width: 50,
    height: 50,
    borderRadius: 10,
    backgroundColor: colors.gray[50],
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.md,
    borderWidth: 1,
    borderColor: colors.gray[200],
  },
  methodTitle: {
    fontSize: typography.fontSize.xl,
    fontWeight: typography.fontWeight.semibold,
    color: colors.gray[800],
    marginBottom: 2,
  },
  methodSubtitle: {
    fontSize: typography.fontSize.base,
    color: colors.gray[500],
  },
  methodExpiry: {
    fontSize: typography.fontSize.sm,
    color: colors.gray[400],
    marginTop: 2,
  },
  deleteIconContainer: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  trashCan: {
    width: 18,
    height: 20,
    position: 'relative',
  },
  trashLid: {
    width: 20,
    height: 2,
    backgroundColor: colors.error,
    position: 'absolute',
    top: 0,
    left: -1,
    borderRadius: 1,
  },
  trashBody: {
    width: 16,
    height: 16,
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: colors.error,
    position: 'absolute',
    top: 4,
    left: 1,
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 4,
  },
  addButton: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
  },
  addButtonText: {
    color: colors.white,
    fontSize: typography.fontSize.xl,
    fontWeight: typography.fontWeight.semibold,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: spacing.xl,
    maxHeight: '90%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  modalTitle: {
    fontSize: typography.fontSize.xxxl,
    fontWeight: typography.fontWeight.semibold,
    color: colors.gray[800],
  },
  closeButton: {
    fontSize: typography.fontSize.massive,
    color: colors.gray[500],
  },
  typeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: spacing.xl,
  },
  typeButton: {
    flex: 1,
    minWidth: '45%',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.gray[300],
    alignItems: 'center',
    backgroundColor: colors.white,
  },
  typeButtonActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primaryLight,
  },
  typeIconSmall: {
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
  },
  visaSmallText: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.bold,
    color: colors.visa,
  },
  mcCircles: {
    flexDirection: 'row',
    width: 24,
  },
  mcCircle: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  mcRed: {
    backgroundColor: colors.mastercardRed,
    marginRight: -4,
  },
  mcOrange: {
    backgroundColor: colors.mastercardOrange,
  },
  appleSmall: {
    width: 16,
    height: 18,
    backgroundColor: colors.black,
    borderRadius: 6,
    position: 'relative',
  },
  appleSmallBite: {
    width: 4,
    height: 4,
    backgroundColor: colors.white,
    borderRadius: 2,
    position: 'absolute',
    top: 2,
    right: 2,
  },
  appleSmallLeaf: {
    width: 4,
    height: 3,
    backgroundColor: colors.black,
    position: 'absolute',
    top: -2,
    right: 6,
    borderTopRightRadius: 2,
  },
  gSmallText: {
    fontSize: typography.fontSize.xl,
    fontWeight: typography.fontWeight.bold,
    color: colors.googleBlue,
  },
  typeText: {
    fontSize: typography.fontSize.md,
    color: colors.gray[500],
    fontWeight: typography.fontWeight.medium,
  },
  typeTextActive: {
    color: colors.primary,
    fontWeight: typography.fontWeight.semibold,
  },
  inputGroup: {
    marginBottom: spacing.lg,
  },
  label: {
    fontSize: typography.fontSize.md,
    fontWeight: typography.fontWeight.medium,
    color: colors.gray[600],
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.gray[300],
    borderRadius: 10,
    paddingVertical: spacing.md,
    paddingHorizontal: 14,
    fontSize: typography.fontSize.lg,
    color: colors.gray[800],
    backgroundColor: colors.white,
  },
  row: {
    flexDirection: 'row',
  },
  infoBox: {
    backgroundColor: '#EFF6FF',
    borderRadius: 10,
    padding: spacing.lg,
    marginBottom: spacing.xl,
  },
  infoText: {
    fontSize: typography.fontSize.base,
    color: '#1E40AF',
    textAlign: 'center',
  },
  submitButton: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 10,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  submitButtonText: {
    color: colors.white,
    fontSize: typography.fontSize.xl,
    fontWeight: typography.fontWeight.semibold,
  },
});

// Styles pour les icônes de paiement
export const paymentIconStyles = StyleSheet.create({
  card: {
    width: 40,
    height: 28,
    backgroundColor: colors.gray[100],
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.gray[300],
  },
  visaText: {
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.bold,
    color: colors.visa,
  },
  mastercardCircles: {
    flexDirection: 'row',
    width: 24,
  },
  circle: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  circleRed: {
    backgroundColor: colors.mastercardRed,
    marginRight: -4,
  },
  circleOrange: {
    backgroundColor: colors.mastercardOrange,
  },
  applePay: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  appleIcon: {
    width: 16,
    height: 18,
    backgroundColor: colors.black,
    borderRadius: 6,
    position: 'relative',
  },
  appleBite: {
    width: 4,
    height: 4,
    backgroundColor: colors.gray[50],
    borderRadius: 2,
    position: 'absolute',
    top: 2,
    right: 2,
  },
  appleLeaf: {
    width: 4,
    height: 3,
    backgroundColor: colors.black,
    position: 'absolute',
    top: -2,
    right: 6,
    borderTopRightRadius: 2,
  },
  appleText: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold,
    color: colors.black,
  },
  googlePay: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  gIcon: {
    width: 18,
    height: 18,
    backgroundColor: colors.googleBlue,
    borderRadius: 9,
    justifyContent: 'center',
    alignItems: 'center',
  },
  gText: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.bold,
    color: colors.white,
  },
  googleText: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.semibold,
    color: colors.googleBlue,
  },
  defaultText: {
    fontSize: typography.fontSize.xxxl,
  },
});
