import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from '../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.background,
  },
  header: {
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.massive,
    paddingBottom: spacing.xl,
    backgroundColor: colors.white,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: colors.gray[200],
  },
  headerTitle: {
    fontSize: typography.fontSize.huge,
    fontWeight: typography.fontWeight.bold,
    color: colors.gray[800],
  },
  scrollContent: {
    paddingVertical: spacing.xxxl,
    paddingHorizontal: spacing.xl,
  },
  profileImageContainer: {
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  imageWrapper: {
    position: 'relative',
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 4,
    borderColor: colors.white,
  },
  placeholderImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: colors.gray[200],
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 4,
    borderColor: colors.white,
  },
  placeholderIconShape: {
    width: 60,
    height: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  placeholderHead: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.gray[400],
    marginBottom: 4,
  },
  placeholderBody: {
    width: 48,
    height: 28,
    backgroundColor: colors.gray[400],
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  editBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: colors.primary,
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: colors.white,
  },
  editIcon: {
    width: 16,
    height: 16,
    position: 'relative',
  },
  pencilBody: {
    width: 2,
    height: 12,
    backgroundColor: colors.white,
    position: 'absolute',
    top: 2,
    left: 7,
    transform: [{ rotate: '45deg' }],
  },
  pencilTip: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 3,
    borderRightWidth: 3,
    borderBottomWidth: 5,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: colors.white,
    position: 'absolute',
    top: 0,
    left: 5,
    transform: [{ rotate: '45deg' }],
  },
  userName: {
    fontSize: typography.fontSize.massive,
    fontWeight: typography.fontWeight.bold,
    color: colors.gray[800],
    textAlign: 'center',
    marginBottom: 4,
  },
  userEmail: {
    fontSize: typography.fontSize.base,
    color: colors.gray[500],
    textAlign: 'center',
    marginBottom: spacing.xxxl,
  },
  menuContainer: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: spacing.sm,
    marginBottom: spacing.xl,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: spacing.lg,
    paddingHorizontal: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray[100],
  },
  menuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  menuIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.md,
  },
  menuIconText: {
    fontSize: spacing.xl,
  },
  menuItemText: {
    fontSize: typography.fontSize.xl,
    color: colors.gray[800],
    fontWeight: typography.fontWeight.medium,
  },
  menuArrow: {
    fontSize: typography.fontSize.massive,
    color: colors.gray[400],
  },
  logoutButton: {
    backgroundColor: colors.error,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 10,
  },
  logoutButtonText: {
    color: colors.white,
    fontSize: typography.fontSize.xl,
    fontWeight: typography.fontWeight.semibold,
  },
});
